name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install --dev --no-ansi -q
      - name: Execute Feature tests via Pest
        run: vendor/bin/pest
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}